export const t = {
  appName: 'משמרותי',
  tagline: 'מעקב משמרות ותשר',

  // Nav
  nav: {
    dashboard: 'לוח בקרה',
    new: 'חדשה',
    history: 'היסטוריה',
    report: 'דוח',
    settings: 'הגדרות',
  },

  // Jobs
  job: {
    wedding: 'אולם אירועים',
    weddingShort: 'אולם',
    hourly: 'שעתי',
    hourlyShort: 'שעתי',
  },

  // Tiles
  tile: {
    today: 'היום',
    week: 'השבוע',
    month: 'החודש',
    lastMonth: 'חודש שעבר',
    split: 'פילוח לפי עבודה',
    trend: '30 ימים אחרונים',
    recent: 'משמרות אחרונות',
    hoursByJob: 'שעות עבודה החודש',
    hoursByJobSubtitle: 'פילוח שעות לפי עבודה',
    effectiveRateTile: 'שכר שעתי אפקטיבי',
    effectiveRateSubtitle: 'איזו עבודה משתלמת יותר לשעה',
    winner: 'משתלמת יותר',
    difference: 'הפרש',
    noShiftsToday: 'אין משמרות היום',
    noShifts: 'אין משמרות עדיין',
    shifts: 'משמרות',
    shift: 'משמרת',
    effectiveRate: 'שכר שעתי אפקטיבי',
    tips: 'טיפים',
    base: 'שכר בסיס',
    expenses: 'הוצאות',
    net: 'נטו',
    hours: 'שעות',
    avgPerShift: 'ממוצע למשמרת',
  },

  // New shift form
  form: {
    title: 'משמרת חדשה',
    date: 'תאריך',
    jobType: 'סוג עבודה',
    startTime: 'שעת התחלה',
    endTime: 'שעת סיום',
    computedHours: 'חושב: {h} שעות',
    overnightHint: 'כולל משמרת לילה שחוצה חצות',
    hours: 'שעות',
    hoursPlaceholder: 'לדוגמה: 6.5',
    timeInvalid: 'זמן לא תקין',
    tips: 'טיפים (₪)',
    tipsPlaceholder: '0',
    expenses: 'הוצאות (₪, אופציונלי)',
    expensesPlaceholder: '0',
    expensesHint: 'אוכל, תחבורה וכו׳ — לא מופחת מהסך',
    notes: 'הערות (אופציונלי)',
    notesPlaceholder: 'משמרת ארוכה, אירוע גדול...',
    inputMode: 'אופן הזנה',
    modeTime: 'לפי שעות התחלה וסיום',
    modeHours: 'הזנה ישירה של שעות',
    basePreview: 'שכר בסיס',
    totalPreview: 'סה"כ משמרת',
    save: 'שמירה',
    cancel: 'ביטול',
    saved: 'נשמר',
    edit: 'עריכת משמרת',
    update: 'עדכון',
    hoursRequired: 'יש להזין שעות',
    hoursInvalid: 'מספר שעות לא תקין',
    tipsInvalid: 'סכום לא תקין',
  },

  // History
  history: {
    title: 'היסטוריה',
    filterAll: 'הכל',
    filterWedding: 'אולם',
    filterHourly: 'שעתי',
    empty: 'אין משמרות להצגה',
    delete: 'מחיקה',
    edit: 'עריכה',
    confirmDelete: 'למחוק את המשמרת?',
  },

  // Settings
  settings: {
    title: 'הגדרות',
    rates: 'תעריפים וסוגי עבודה',
    weddingName: 'שם עבודה 1 (שכר יומי)',
    weddingRate: 'שכר יומי (₪)',
    hourlyName: 'שם עבודה 2 (שעתי)',
    hourlyRate: 'תעריף שעתי (₪)',
    saveSettings: 'שמירת הגדרות',
    settingsSaved: 'ההגדרות נשמרו',
    rateHint: 'שינוי תעריף ישפיע רק על משמרות חדשות',
    data: 'נתונים',
    exportCsv: 'ייצוא ל-CSV',
    exportJson: 'ייצוא גיבוי (JSON)',
    importJson: 'ייבוא גיבוי (JSON)',
    clearAll: 'מחיקת כל הנתונים',
    clearConfirm: 'זה ימחק את כל המשמרות. האם אתה בטוח?',
    imported: 'ייובאו {n} משמרות',
    about: 'אודות',
    version: 'גרסה',
    builtBy: 'נבנה ע"י תאמר עדוי',
    linkedin: 'לינקדאין',
  },

  // Common
  common: {
    ils: '₪',
    perHour: '₪/שעה',
    back: 'חזרה',
    close: 'סגירה',
  },

  // Auth
  auth: {
    welcome: 'ברוכים הבאים',
    welcomeBack: 'ברוכים השבים',
    signInTitle: 'התחברות',
    signUpTitle: 'הרשמה',
    signInSubtitle: 'הזן את הפרטים שלך כדי להמשיך',
    signUpSubtitle: 'צור חשבון חדש כדי להתחיל לעקוב',
    email: 'אימייל',
    password: 'סיסמה',
    passwordHint: 'לפחות 6 תווים',
    emailPlaceholder: 'name@example.com',
    signIn: 'התחבר',
    signUp: 'הירשם',
    signOut: 'התנתק',
    orContinueWith: 'או המשך עם',
    google: 'Google',
    haveAccount: 'כבר יש לך חשבון?',
    noAccount: 'אין לך חשבון?',
    switchToSignIn: 'התחבר',
    switchToSignUp: 'הירשם כאן',
    loading: 'טוען...',
    confirmEmail: 'שלחנו לך מייל אישור. בדוק את תיבת הדואר.',
    invalidEmail: 'אימייל לא תקין',
    weakPassword: 'סיסמה חייבת להיות לפחות 6 תווים',
    signedInAs: 'מחובר כ',
  },

  // Report
  report: {
    title: 'דוח חודשי',
    subtitle: 'דוח משמרות מפורט',
    generate: 'יצירת דוח PDF',
    pickMonth: 'בחר חודש',
    include: 'מה לכלול בדוח',
    includeSummary: 'סיכום (סה"כ, שעות, ממוצעים)',
    includeJobBreakdown: 'פילוח לפי עבודה',
    includeEffectiveRate: 'שכר שעתי אפקטיבי',
    includeShifts: 'רשימת משמרות מלאה',
    includeTips: 'טיפים',
    includeExpenses: 'הוצאות',
    includeNotes: 'הערות',
    downloadPdf: 'הורדת PDF',
    generatingPdf: 'מכין דוח...',
    noData: 'אין נתונים בחודש זה',
    generatedOn: 'הופק בתאריך',
    reportFor: 'דוח עבור',
    summary: 'סיכום',
    byJob: 'פילוח לפי עבודה',
    shifts: 'משמרות',
    effectiveRate: 'שכר שעתי אפקטיבי',
    winnerText: '{job} משתלמת יותר ב-{diff} לשעה',
    totalGross: 'סה"כ ברוטו',
    totalHours: 'סה"כ שעות',
    shiftCount: 'מספר משמרות',
    avgPerShift: 'ממוצע למשמרת',
    avgPerHour: 'ממוצע לשעה',
    page: 'עמוד',
  },
} as const
